name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: chmod +x gradlew
      - run: echo $(git describe --always --tags)

      - name: Build
        run: ./gradlew build -Pcommit="$(git describe --always --tags | grep -oP '[-](.*)' | cut -c2-)"

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs
